### ISSUE TITLE
Build time significantly increases with custom_icons

### ISSUE THREAD

**Issue by kcgthb** [facelessuser/mkdocs-material-extensions#14]
_This is a followup / repost of https://github.com/squidfunk/mkdocs-material/issues/1942_

## Description

The site build time significantly increases (x8) when additional icons are enabled via `custom_icons`.

### Expected behavior

Same, or at least comparable build times with or without additional icons.

### Actual behavior

- without additional icons:
  ```
  $ grep -A3 pymdownx.emoji mkdocs.yml
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:pymdownx.emoji.to_svg
        #    options:
        #  custom_icons:
        #    - overrides/.icons
  $ time mkdocs -q build
  
  real    0m8.947s
  user    0m8.744s
  sys     0m0.645s
  ```

* with additional icons:
  ```
  $ grep -A3 pymdownx.emoji mkdocs.yml
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:pymdownx.emoji.to_svg
        options:
          custom_icons:
            - overrides/.icons
  $ time mkdocs -q build
  
  real    0m57.974s
  user    0m50.919s
  sys     0m7.643s
  ```

The actual icons don't seem to matter, nor the number of icons in `overrides/.icons`.

What seems to be happening is that with `custom_icons` enabled, `mkdocs` spends more and more time to read each page, as it's progressing through them. In verbose mode you can see that each of the lines:
```
DEBUG   -  Reading: docs/page.md
```
takes longer to process than the previous one, and end up almost crawling to a halt.
Without `custom_icons`, the build process goes through all of then quickly, each page taking the same time to read.

### Steps to reproduce the bug

1. enable custom icons in `mkdocs.yml` as per [the materials for MkDocs documentation](https://squidfunk.github.io/mkdocs-material/setup/changing-the-logo-and-icons/#additional-icons)
2. build the pages with `mdocs build` or `mkdocs serve`

### Package versions

* Python: `Python 3.7.8`
* MkDocs: `mkdocs, version 1.1.2`
* mkdocs-material-extensions: 1.0

**Comment by facelessuser** [comment]
@kcgthb can you check `master` out? Apparently, my recent fix is there, but I never released it.

**Comment by kcgthb** [comment]
It look like the the fix from `master` is working well!
Build times are identical with or without `custom_icons` now. :tada:

**Comment by facelessuser** [comment]
🤦‍♂️ So I fixed it and never released it. Sounds about right 😆.

**Comment by facelessuser** [comment]
It is now released

**Comment by kcgthb** [comment]
Thank you very much!
