### ISSUE TITLE
Non-Pre Release

### ISSUE THREAD

**Issue by NJAldwin** [facelessuser/mkdocs-material-extensions#2]
Please consider cutting a new release that does not include pre-release specifiers (currently `1.0b1`).

---

I ran into this issue when updating a `mkdocs-material` site to `mkdocs` 1.1 and `mkdocs-material` 5.x.  `mkdocs-material` relies on` mkdocs-material-extensions>=1.0b1` (presumably as that's the latest release): https://github.com/squidfunk/mkdocs-material/blob/c5f9c53116e974e6027c216cd6e5103e636d44e1/requirements.txt#L26

This caused issues with our site, the environment of which is managed by `pipenv`.  It seems that `pipenv` considers `1.0b1` to be a "pre-release" due to the `b1` specifier.  I believe this is because it is attempting to apply semver rules (though under semver, there would be a `-` before `b1`).  Regardless,  this means that pipenv is unable to set up the environment without forcing it to allow pre-releases (which is not ideal for production).

If `1.0b1` is stable (or "stable enough" to be included in a stable release of `mkdocs-material`), please consider a new `1.0` release so that downstream consumers can use a stable version without allowing pre-release versions into the environment.

(If you consider this to be a `mkdocs-material` problem as that project is depending on a pre-release version, I am happy to open an issue in that repo.  Let me know.  I'll note that with no other `mkdocs-material-extensions` releases, it seems that the only solution on the `mkdocs-material` side would be to stop using this library until it has a stable release)

**Comment by facelessuser** [comment]
I've always planned to release a stable version...as soon as it is ready. It is a pre-release because I'm not confident yet that I won't change anything in it yet. I released it as a pre-release to get feedback. Material chose to ship it ASAP. As soon as I am confident that what I have presented is final, I will release a final. It is possible that Material can make it optional, but I am not quite ready to release a final. But as soon as I am, I will make sure to do so.

@gir-bot remove S: triage
@gir-bot add T: support

**Comment by squidfunk** [comment]
In the meantime you may use `mkdocs-material<5.1` which doesn’t include the dependency or fork the theme to explicitly remove it.

**Comment by facelessuser** [comment]
I will close this issue as we will continue to work towards a final release. Beta 2 (paired with pymdown-extensions 7.1) will provide a solution for local custom icon assets. It may very well be the last beta as long as long as no issues arise.
