### ISSUE TITLE
typo in pyproject.toml

### ISSUE THREAD

**Issue by eUgEntOptIc44** [facelessuser/mkdocs-material-extensions#21]
Hi @facelessuser 

I just noticed the following typo in line 27 of [pyproject.toml](https://github.com/facelessuser/mkdocs-material-extensions/blob/68abe89238e9131855dae45d9e97b08d31c95f33/pyproject.toml#L27).

```toml
Homepage = "https://github.com/facelessuser/mkdocs-material-extensions'"
```

The last char of the url is a single quote. So the url is invalid right now.

Hope this might be helpful.

Regards, Jean-Luc

**Comment by facelessuser** [comment]
Thanks for the issue. It was a typo introduced during the switch to a new build system for the project.
