### ISSUE TITLE
[Feature Request] YouTube Embeds

### ISSUE THREAD

**Issue by Stanzilla** [facelessuser/mkdocs-material-extensions#3]
I'm not sure what your intentions for this project are, but I currently do some very ugly hacks in JavaScript at the moment to get a few missing Markdown features working.

One of them is a tag for YouTube embeds. Currently I'm scanning the `alt` tag of images for `YOUTUBE` and then replace the image with an iframe like so:

```js
const elements = document.querySelectorAll("img[alt=\"YOUTUBE\"]")

  Array.prototype.forEach.call(elements, (el, i) => {
    const id = el.getAttribute("title").split("/")[el.getAttribute("title").split("/").length - 1]
    const oldClass = el.getAttribute("class")
    const iframe = document.createElement("iframe")

    iframe.title = "YouTube"
    iframe.src = `https://www.youtube.com/embed/${id}?modestbranding=1&amp;`

    if (oldClass !== "null") {
      iframe.className = `video-embed ${oldClass}`
    } else {
      iframe.className = "video-embed"
    }

    el.replaceWith(iframe)
  })
```

Now if we could do this natively and on compile instead of run, that would be great.

**Comment by facelessuser** [comment]
This repository is meant to be a place for things too specific for Material that they don't make sense in pymdown-extensions. I'm also selective as to what I wish to support as anyone can create their own Markdown extensions -- I'm not meant to be the one stop shop for anything Markdown extension related 🙂.

Both Martin and I thought inlining Material icon assets would be cool, but it was too complicated fro Martin to maintain (not enough confidence with Python) and too specific to a particular project (mkdocs-material) to be included in the general purpose `pymdown-extensions`.

This project is meant to hold things of this nature. Inlining Material assets may be the only thing it ever contains, but maybe it will contain more 🤷‍♂️ .

As far as this request is concerned, `pymdown-extensions` would be a better place to request something like this as what you are suggesting isn't really Material specific.

With that said, aren't there already Python Markdown extensions that do stuff like this?

@gir-bot remove S: triage
@gir-bot add S: wontfix

**Comment by Stanzilla** [comment]
Makes sense and not that I'm aware of?
