### ISSUE TITLE
Custom icons are not available with the markdown syntax

### ISSUE THREAD

**Issue by diba1013** [facelessuser/mkdocs-material-extensions#5]
# Description

When adding custom icons as described with squidfunk/mkdocs-material#1620, I want to use them not only in the `mkdocs.yml` but also from within markdown.

Two potential setups come to mind:

1. Add custom icons within a new namespace (e.g. `bootstrap`)
2. Overwrite icons from an exisiting namespace (e.g. `fontawesome/brands`) *Not sure why you want to do that, but it is technically possible*

## Setup

1. I use the exact same setup that mkdocs-material [recommends](https://squidfunk.github.io/mkdocs-material/extensions/pymdown/#icons).
2. I specify the `mkdocs-material-extension` within `requirements.txt` as it is not pulled by pip yet (I assume since mkdocs throws errors without).

## Working example

I will use the following directory structure, a working example can be found at [mkdocs-material-playground](https://diba1013.github.io/mkdocs-material-playground/) on the "Home" page:

```yaml
theme: 
    name: material
    custom_dir: theme

    icon:
        logo: bootstrap/circle-square
```

```
docs
    index.md
theme
    .icons 
        bootstrap
            circle-square.svg (newly added)
        fontawesome
            brands
                git-alt.svg (replaced with bootstrap/app.svg)
mkdocs.yml
```

and the icons from a markdown file:

```md
1. Default icon: :material-pen:
2. Bootstrap custom icon: :bootstrap-circle-square:
3. Fontawesome overwritten icon: :fontawesome-brands-git-alt:
```

Note that I have purposefully overwritten `fontawesome/brands/git-alt.svg` to see what mkdocs-material does with it. It is correctly displayed as repository icon (However, as noted above, I am not sure if that is really a use case to consider).

*I have a [custom stylesheet](https://github.com/diba1013/mkdocs-material-playground/blob/feature/icons-in-markdown/theme/assets/stylesheets/vendor/mkdocs-material.css) in place which scales the icons to the correct size.*

## Expectation

Following the naming schema as described in the readme, I would assume that the new icons are available from within markdown.

1. Default icon is displayed (as proof it is working). *This works.*
2. Custom icon should be displayed. *This is not replaced*
3. Overwritten icon should be changed (see above). *The original icon is displayed.*

## Solution

While I do not fully understand how your extension integrates into mkdocs, I assume that you get the icons from within mkdocs-material folder via [this line](https://github.com/facelessuser/mkdocs-material-extensions/blob/master/materialx/emoji.py#L15). 

If it is at all possible that you access the custom `.icons` folder, they should be loaded first, so that the `index` is populated before loading those from `mkdocs-material/material/.icons`.

**Comment by facelessuser** [comment]
This is not currently supported, and the extension has no way of knowing where your custom icons are.  The way we currently do this is we acquire Material's install path and then search the `.icons` folder for icons.  I would have to add a way to communicate paths to the emoji_index builder, which is not currently available. Currently there is no promise that custom icons will work in Markdown content.

I can consider this, but I need to expose passing options to the index builder in `pymdownx.emoji`. Once we do that, I can configure this to take into considerations multiple source directories.

As this is a beta, the custom issue was known, and I had been considering possibilities as to if and how I would approach this. This is why there is no formal release yet. But keep in mind , this is not a bug as the first beta was only meant to handle Material's official icons.

@gir-bot remove S: triage
@gir-bot add T: feature

**Comment by diba1013** [comment]
> But keep in mind , this is not a bug as the first beta was only meant to handle Material's official icons.

Thanks for the feedback. I will keep my [branch](https://github.com/diba1013/mkdocs-material-playground/tree/feature/icons-in-markdown) in my repository in case you want to reference it for an implementation.

**Comment by facelessuser** [comment]
This change in `pymdownx.emoji` should allow us to change our implementation to accept user defined icon sources: https://github.com/facelessuser/pymdown-extensions/pull/900.

**Comment by facelessuser** [comment]
Custom icons should now be possible with `pymdown-extensions` 7.1 and `mkdocs-material-extensions` 1.0b2. Feel free to create a new issue if you run into issues.
