### ISSUE TITLE
Github Page is down

### ISSUE THREAD

**Issue by XenoPhex** [facelessuser/mkdocs-material-extensions#7]
While trying to figure out the emoji syntax, I tried clicking all the links in the README and all of them 404. It looks like https://facelessuser.github.io/mkdocs-material-extensions/extensions/emoji no longer exists.

This site being down / no real documentation on the emoji naming scheme is making it difficult to figure out what an emoji's name is in markdown. I've spend quite some time trying to figure out how to get the windows logo to work, knowing that it's in font awesome.

**Comment by facelessuser** [comment]
The links are bad, it's supposed to link to the `pymdown-extensions` project, not `mkdocs-material-extensions`. I think it was a find / replace issue. So I'd replace accordingly and you'll be fine.

The documentation for `pymdownx.emoji` is here: https://facelessuser.github.io/pymdown-extensions/extensions/emoji/.

**Comment by facelessuser** [comment]
@gir-bot remove S: triage
@gir-bot add T: bug, C: docs
