### ISSUE TITLE
conda-recipe

### ISSUE THREAD

**Issue by pkestene** [facelessuser/mkdocs-material-extensions#9]
I wanted to try a newer mkdocs-material, but noticed that current version of it requires your package
for which there is no conda-forge recipe yet, if I'm not mistaken.

I'm not used to it, but I tried to write a recipe based on the offical example, here it is:
 https://github.com/pkestene/staged-recipes/tree/recipe/mkdocs-material-extensions/recipes/mkdocs-material-extensions

let me know if it's ok or not or if you prefer to submit a recipe yourself.

**Comment by facelessuser** [comment]
I never supply any conda recipes. All conda recipes that I'm aware of are supported by unknown entities to me, so I don't mind who does it. I support the PyPI releases and that is usually it.

@gir-bot remove S: triage

**Comment by pkestene** [comment]
ok thanks. So i'll submit the recipe.
Are you willing to be listed as a maintainer for the recipe ?
